# Generated by Django 5.0.3 on 2024-03-19 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_user_id', message='User ID must be in the format USR followed by 5 digits', regex='^USR\\d{5}$')])),
                ('user_fname', models.CharField(max_length=15)),
                ('user_mname', models.CharField(max_length=15, null=True)),
                ('user_lname', models.CharField(max_length=15, null=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=20, unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
